/* Bremen City Walk — offline service worker
   GENERATED by build.mjs — edit templates/sw.js, then run `node build.mjs`.

   Precaches everything on install (per-file, with retry, failures visible),
   serves cache-first, and answers HTTP Range requests from cache (required
   for audio playback on iOS Safari while offline). */

const CACHE_NAME = '__CACHE_NAME__';

const ASSETS = __ASSETS__;

/* Fetch every asset that is not cached yet. Per-file with one retry —
   unlike cache.addAll(), a single failed download no longer kills the
   whole installation silently; the page can show what's missing. */
let settling = null;
async function precache() {
  const cache = await caches.open(CACHE_NAME);
  const jobs = ASSETS.map(async url => {
    if (await cache.match(url, { ignoreSearch: true })) return;
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        // cache:'reload' bypasses the browser HTTP cache, so a new SW version
        // always precaches the freshest files from the server
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (!res.ok) throw new Error('HTTP ' + res.status);
        await cache.put(url, res);
        return;
      } catch (err) { /* retry once, then leave it missing */ }
    }
  });
  settling = Promise.allSettled(jobs).then(() => { settling = null; });
  return settling;
}

self.addEventListener('install', event => {
  event.waitUntil(precache().then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

/* Page asks "how much is saved?" — reply with progress; on RETRY,
   attempt the missing files again (precache skips what's cached). */
self.addEventListener('message', event => {
  if (!event.data) return;
  if (event.data.type === 'STATUS') {
    caches.open(CACHE_NAME)
      .then(async cache => {
        const misses = [];
        for (const url of ASSETS) {
          if (!(await cache.match(url, { ignoreSearch: true }))) misses.push(url);
        }
        event.ports[0].postMessage({
          cached: ASSETS.length - misses.length,
          total: ASSETS.length,
          missing: misses.length,
          settled: settling === null,
        });
      });
  } else if (event.data.type === 'RETRY') {
    precache();
  }
});

/* Serve a partial (206) response from a fully cached body. */
async function rangeResponse(request, response) {
  const rangeHeader = request.headers.get('range');
  const match = /bytes=(\d+)-(\d*)/.exec(rangeHeader);
  if (!match) return response;
  const buffer = await response.arrayBuffer();
  const size = buffer.byteLength;
  const start = Number(match[1]);
  const end = match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  return new Response(buffer.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': response.headers.get('Content-Type') || 'application/octet-stream',
      'Content-Range': `bytes ${start}-${end}/${size}`,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes',
    },
  });
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    // ignoreSearch: tolerate cache-busting query strings
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) {
      if (request.headers.has('range')) return rangeResponse(request, cached);
      return cached;
    }
    try {
      return await fetch(request);
    } catch (err) {
      // offline navigation fallback
      if (request.mode === 'navigate') {
        const index = await cache.match('./index.html');
        if (index) return index;
      }
      throw err;
    }
  })());
});
